[project]
name = "ai-agent-fwork-sandpit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-framework>=1.0.0b251001",
    "dotenv>=0.9.9",
    "python-dotenv>=1.1.1",
]
